import React from "react";
import Nav from "./Nav";
import Head from "next/head";
import Footer from "./Footer";

export default function Layout({ children }) {
  return (
    // Beginning for all pages as this is the default layout -- Defines the pages outlook
    <div className="components">
      {/* Beginning of the head component of the webpages */}

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital@1&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        />
        <script
      
          id = "my-script"
          src = "/script/script.js"
          type = "text/javascript"
        >
        </script>
      </Head>

      {/* End of the head component of the webpages */}

      {/* Layout Defination --All Pages will come below the Nav Component as indicated */}

      <Nav />
      {children}
      <Footer />
    </div>

    // Beginning for all pages as this is the default layout -- Defines the pages outlook
  );
}

export async function getStaticProps(context) {
  const res = await axios({
    method: "GET",
    url: "http://localhost:9000/getProducts",
  });

  console.log(res);

  const data = res.data;

  return {
    props: {
      data,
    },
  };
}
